### PR TITLE
fix: replace deprecated `url.parse()` with `new URL()`

### PR DESCRIPTION
**Pull request by alumni**
## Checklist

- [x] I have ensured my pull request is not behind the main or master branch of the original repository.
- [x] I have rebased all commits where necessary so that reviewing this pull request can be done without having to merge it first.
- [x] I have written a commit message that passes commitlint linting.
- [x] I have ensured that my code changes pass linting tests.
- [x] I have ensured that my code changes pass unit tests.
- [x] I have described my pull request and the reasons for code changes along with context if necessary.

Replaces the other occurrences of `url.parse()` with `new URL()`. Continuation of PR #1802.

### CODE REVIEW

**Comment by foresterre** [comment]
This is possibly a breaking change. Previously, a value like "0.0.0.0" was accepted, while it now errors with "0.0.0.0 is not a valid URL"

**Comment by gramakri** [comment]
@alumni I think this change broke IPv6 queries. See https://github.com/ladjs/superagent/pull/1805 . The change makes node resolve [x]:port as a hostname instead of IPv6 address.

**Comment by alumni** [comment]
There's a pr open to fix it ;)

**Comment by gramakri** [comment]
@alumni ah, I was hoping you would review that PR  :-D (also, there was an edit in that PR saying it's hard to test)

**Pull request merged**
